### ISSUE TITLE
Immutabilité 

### ISSUE THREAD

**Issue by bzah** [known-as-bmf/known-as-bmf-gatsby#1]
...intro/part-2.md

"Une valeur immuable est une valeur qui change pas de valeur après sa définition. Pour faire muter cette valeur, il faut d'abord en faire une copie."

C'est assez confus je trouve, il faudrait reformuler. 
D'autant que l'immutabilité n'a de sens que pour les objets ou collections et pour les types primitifs on parle simplement de constantes.

**Comment by known-as-bmf** [comment]
Je suis d'accord que c'est peu compréhensible. J'ai écrit ça hier soir et je ne savais pas trop comment l'expliquer 😅

Cette page est assez indigeste (a séparer en deux potentiellement).

Objets, collection et aussi strings il me semble

Que pensez tu de 

> Une variable immuable est une variable qui ne doit pas changer de valeur après sa définition. C'est surtout pertinent pour les objets, et les collections car les primitives sont généralement manipulées par valeur.
> 
> Pour faire muter une variable immuable, il faut d'abord en faire une copie, puis transformer cette copie.
